---
title: "TidyTuesday"
author: "Lucas Kopecky Bobadilla"
date: "6/01/2021"
output: html_document
---

## Packages

```{r include=FALSE}
library(tidyverse)
library(tidytuesdayR)
library(patchwork)
library(ggridges)
library(survivoR)

```


## Data

If necessary install the package `tidyTuesdayR` to get the data using `install.packages("tidytuesdayR")`:

```{r message=FALSE, warning=FALSE, include=FALSE}

summ_df<- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-06-01/summary.csv')

chall_df<- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-06-01/challenges.csv')

cast_df <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-06-01/castaways.csv')

viewers_df <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-06-01/viewers.csv')

jury_votes_df <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-06-01/jury_votes.csv')
```

### Data structure and cleaning

```{r}
# data structure
glimpse(summ_df)

# to factor
summ_df$country <- factor(summ_df$country)

```

```{r}
# plot 1 - heatmap with countries with more programs
summ_df %>% 
  group_by(country) %>% 
  summarize(count = n())

# number of times each winner participates
summ_df %>% 
  group_by(factor(full_name)) %>% 
  summarize(count = n())

# get each season length

summ_df <- summ_df %>% 
  mutate(season_length = ended - premiered,
         filming_length = filming_ended - filming_started)


```

```{r}
# map
library("rnaturalearth")
library("rnaturalearthdata")
library("ggspatial")
library(ggthemes)
library(ggrepel)
world <- map_data("world")

world <- world %>% 
  full_join(summ_df %>% 
  group_by(country) %>% 
  summarize(season = n()) %>% 
    rename(region = country)) %>% 
  mutate(`Total of seasons` = if_else(is.na(as.double(season)), 0,as.double(season)))

map <- ggplot() +
  geom_map(data = world, map = world,
    aes(long, lat, map_id = region, fill = `Total of seasons`), color = "grey") +
  scale_fill_gradient(low="grey", high="red", breaks=c(0,2,5,9)) +
  labs(title = "Survivor: Season locations") +
  theme_wsj() +
  theme(legend.box.just = "right")



```

```{r}
# challenges

glimpse(chall_df)

fac <- c('season_name', "title","episode","season","winners", "winning_tribe", "challenge_type")
chall_df[fac] <- lapply(chall_df[fac], factor)

chall_df %>% 
  group_by(season, winners, challenge_type) %>%
  summarize(count = n()) %>% 
  arrange(season, challenge_type, desc(count)) %>% 
  group_by(season, challenge_type) %>% 
  filter(count == max(count)) %>% 
  distinct(season, .keep_all = T) %>% 
  full_join(summ_df %>% 
              mutate(season = factor(season)) %>% 
                       select(season, season_winner = winner)) %>% 
  mutate(was_winner = if_else(winners == season_winner,1,0)) %>% 
  ggplot(aes(y = season, x = was_winner)) + 
  geom_text(aes(label = winners, col = factor(was_winner)), face ="bold", show.legend = FALSE) + 
  geom_point(alpha = 0, aes(y = season, x = was_winner, col = factor(was_winner))) +
               facet_grid(.~challenge_type) +
  guides(colour = guide_legend("Season winner", override.aes = list(size = 2, alpha = 1))) +
  labs(x = "", title = "Survivor challenges winners: Were they the season winners?") +
  theme(legend.position = "top")
  
  

```

